version: '3.4'

services:
  express-typescript:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: 'app-express-typescript'
    working_dir: /src
    volumes:
      - .:/src
    environment:
      - NODE_ENV=development
      - REDIS_QUEUE_HOST=redis
      - GGOGLE_ID=
      - GOOGLE_SECRET=
    ports:
      - "5000:5000"
      - "4040:4040"
#    command: yarn nodemon -q -L -w src src/main.ts

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    expose:
      - 6379

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    expose:
      - 27017
